### ISSUE TITLE
Publish NuGet

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/TorchSharp#10]
Completed the packaging of the NuGet, now need to use the Publish feature.

Needed:

* Script to adjust the NuGet package version based on the branch name
* Try it out :-)

**Comment by markusweimer** [comment]
> Will the nuget package include native payload for windows as well?

It already does :) See `/runtimes/win7-x64/native` in the package. This is currently based on an internal build of `libtorch`, pending an official Windows binary from the PyTorch project.

**Comment by mdabros** [comment]
@markusweimer Very nice! Next time I will investigate more closely before asking :-)

**Comment by interesaaat** [comment]
We need to fix this to point to the [new pipeline](https://github.com/xamarin/TorchSharp/blob/master/build/vsts-ci.yml).

**Comment by dsyme** [comment]
I will close this as some nugets are now pushed for libtorch and TorchSharp packages after recent updates (though everything is still very much "preliminary")
