### ISSUE TITLE
Recurrent layers?

### ISSUE THREAD

**Issue by chrisk477** [xamarin/TorchSharp#122]
Hi,

I wanted to ask whether it is within the scope of this project to implement the recurrent neural network layers (e.g. LSTM) that are present in the pytorch framework at some point?

**Comment by interesaaat** [comment]
Hello! In theory the scope of the project is to try to mirror PyTorch as much as we can (time permitting). I just checked and adding LSTM should be fairly easy. I am currently not working on it, but if it's important for you we accept PRs :)

**Comment by dsyme** [comment]
@NiklasGustafsson You may want to address this one in your current work?

**Comment by NiklasGustafsson** [comment]
I'll take a look. It should not be too complicated.
