### ISSUE TITLE
Remove NetFX build from this repo

### ISSUE THREAD

**Issue by dsyme** [xamarin/TorchSharp#128]
I think we should remove the .NET Framework build from this repo, in aid of simplification, and just focus on .NET Core.

@interesaaat @migueldeicaza That ok?

**Comment by dsyme** [comment]
@interesaaat Just to let you know that @migueldeicaza has granted me co-maintainer rights in this repo and for the nuget packages

My aim is limited - to get to the point where we can use the libtorch tensor implementation as the backend for DiffSharp, see https://github.com/DiffSharp/DiffSharp/pull/106.  Roughly I expect this will mean:

* [ ] Get changes such as https://github.com/xamarin/TorchSharp/pull/127
* [ ] Update the nuget packages 
* [ ] Update TorchSharp to more recent pytorch redist
* [ ] Simplify TorchSharp where it makes sense for a long term trajectory (e.g. this issue)

**Comment by interesaaat** [comment]
I am all for it!

**Comment by migueldeicaza** [comment]
Sure - it is just that .NET Core is still slower to build/debug than .NET Framework is on Mac, hence why I prefer those.   But I am not working on this anymore, so up to you Don.

**Comment by gbaydin** [comment]
> @interesaaat Just to let you know that @migueldeicaza has granted me co-maintainer rights in this repo and for the nuget packages
> 
> My aim is limited - to get to the point where we can use the libtorch tensor implementation as the backend for DiffSharp, see [DiffSharp/DiffSharp#106](https://github.com/DiffSharp/DiffSharp/pull/106). Roughly I expect this will mean:
> 
> * [ ]  Get changes such as #127
> * [ ]  Update the nuget packages
> * [ ]  Update TorchSharp to more recent pytorch redist
> * [ ]  Simplify TorchSharp where it makes sense for a long term trajectory (e.g. this issue)

This is awesome!
