### ISSUE TITLE
Re-enable Mac support on CI system

### ISSUE THREAD

**Issue by dsyme** [xamarin/TorchSharp#135]
Mac support has been removed from the CI system because C++ code using the PyTorch 1.5.0 C++ API requires building on later Mac images and XCode toolchains than the Azure Pipeline permissions currently allow

I've asked @migueldeicaza for the necessary permissions

Support was removed here: 

https://github.com/xamarin/TorchSharp/pull/133/commits/8bb6e939d9475de06240b39e56f945d15ed7770a

**Comment by NiklasGustafsson** [comment]
This was addressed a while ago.
