### ISSUE TITLE
tensor.print() - Missing default "newLine" Parameter

### ISSUE THREAD

**Issue by ghost** [xamarin/TorchSharp#1414]
**Introduction:**

After the PR https://github.com/dotnet/TorchSharp/pull/635 ; default `newLine` character for `tensor.print()` became `""` from `"\n"`.

In the Jupyter notebook runs, output of the following code looks incorrect due to missing `newLine`:

Code:
```c#
var tensor = torch.ones(2,2);
tensor.print();
```
Output:
![Image](https://github.com/user-attachments/assets/5921389d-ca7d-4341-9229-8cf349402a25)

===

When we especially add `newLine`, output is shown in correct format:

Code:
```c#
tensor.print(newLine:"\n");
```

Output:
![Image](https://github.com/user-attachments/assets/a42a697d-2a37-4ca8-b895-6c79f51a8b31)

**Comment by yueyinqiu** [comment]
Maybe we need an announcements here #479 ? @NiklasGustafsson
