### ISSUE TITLE
Add an EditorConfig

### ISSUE THREAD

**Issue by markusweimer** [xamarin/TorchSharp#15]
We should add an [EditorConfig](https://editorconfig.org/) to this project. I suggest we clone the one used by corefx or such.

**Comment by markusweimer** [comment]
Turns out corefx doesn't seem to have one. But [this](https://docs.microsoft.com/en-us/visualstudio/ide/editorconfig-code-style-settings-reference?view=vs-2017#example-editorconfig-file) looks pretty authoritative. We should consider using it.

**Comment by migueldeicaza** [comment]
Just validate that it does not reformat my source, which is using the Mono coding style.

**Comment by markusweimer** [comment]
> Just validate that it does not reformat my source, which is using the Mono coding style.

Is there a EditorConfig for that code style we can copy?

**Comment by migueldeicaza** [comment]
Just got pointed out to this one, will try this weekend:
https://github.com/mono/monodevelop/blob/master/.editorconfig
