### ISSUE TITLE
libtorch nuget versions

### ISSUE THREAD

**Issue by gbaydin** [xamarin/TorchSharp#151]
Hi @dsyme I have a question about the latest packaging changes for `libtorch` in nuget. An example for https://www.nuget.org/packages/libtorch-cpu/ is below:

![image](https://user-images.githubusercontent.com/5365982/83951507-b6124e80-a829-11ea-8c0d-ad101dfe55aa.png)

My question is where do the numbers `1.5.5` and `1.5.6` come from. I'm wondering about the following:
- Note that libtorch 1.5.5 and 1.5.6 do not exist. The latest release of PyTorch is currently 1.5.0 https://github.com/pytorch/pytorch/releases/tag/v1.5.0 and the corresponding libtorch is https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.5.0.zip 
- When I see a package called `libtorch-cpu 1.5.5` on nuget I would expect it to hold libtorch 1.5.5 in it, but it doesn't. This is confusing for a user.
- What will happen when one day PyTorch project releases version `1.5.5`? What will be the version of the corresponding nuget libtorch package? 
- Could we introduce some versioning scheme in nuget packages that clearly identifies the libtorch version within each package? I think this is really important for the longer term.

I propose the following versioning:

| PyTorch/libtorch binary version  | Nuget packpage version | Explanation |
|--|--|--|
|1.5.0 | 1.5.0.0 | libtorch 1.5.0 released, first nuget package for libtorch 1.5.0 |
|1.5.0 | 1.5.0.1 | Updated nuget package for libtorch 1.5.0 |
|1.5.0 | 1.5.0.2 | Updated nuget package for libtorch 1.5.0 |
|1.5.0 | ... | Updated nuget package for libtorch 1.5.0 |
|1.5.1 | 1.5.1.0 | libtorch 1.5.1 released, first nuget package for libtorch 1.5.1 |
|1.5.1 | 1.5.1.1 | Updated nuget package for libtorch 1.5.1 |
|1.5.1 | 1.5.1.2 | Updated nuget package for libtorch 1.5.1 |
|1.5.0 | ... | Updated nuget package for libtorch 1.5.1 |

**Comment by dsyme** [comment]
We will adopt a version numbering like this on the next release of PyTorch (1.6.x).

**Comment by dsyme** [comment]
I'll close this as we can't specifically fix it until we consume the next PyTorch update
