### ISSUE TITLE
Discussion: Disposal and TorchTensor structness

### ISSUE THREAD

**Issue by dsyme** [xamarin/TorchSharp#152]
@interesaaat @migueldeicaza  I have a question about the decision to make TorchTensor a struct

TorchTensor captures an unmanaged resources and these resources need to be reliably freed.  The normal way to do this in .NET code is to add a finalizer on an object wrapper. 

However TorchTensor became a struct, and so this places the burden on the user of TorchTensor to hold the TorchTensor in a class and add a finalizer to that.

That is an OK and in DiffSharp we do have an object that can act as this holder.   But I just wanted to check that we are ok with this design.

Additionally, since such a holder must necessarily be a unique holding object - you can't copy the struct around feeely and dispose it multiple times.

How important is it to make TorchTensor a struct anyway?  It feels like it is optimizing the wrong thing unless tensors really are small.

Looking about how I've been coding with TorchTensors in DiffSharp, as an example, I've been freely writing code like this (F# syntax, but the same applies in C#):
```fsharp
tt.[4].DataItem<double>()
```
and that code is incorrect - it would have to be 
```fsharp
use tt2 = tt[4]
return tt2.DataItem<double>()
```
to ensure correct disposal.  There is no warning here, no guidance, you're just left exposed. That's too buggy for my liking, an optimization that might be accessible via some low level `TorchValueTensor` but not for the type exposed in the most common programming model.

**Comment by dsyme** [comment]
See also https://github.com/DiffSharp/DiffSharp/pull/133

**Comment by dsyme** [comment]
TBH my proposal is

1. We make TorchTensor a class (wrapping the existing ref-counted C++ `shared_ptr*`)

2. In the long term we consider adding a `TorchTensorImpl` which is a struct wrapping a non-ref-counted C++ `at::TensorImpl *` pointer (thus eliminating two allocations - one .NET TorchTensor and one C++ `at::Tensor` reference counted wrapper).  

The half-way house we have at the moment TorchTensor is a struct wrapping an inaccurately-counted `at::Tensor` just seems wrong.

**Comment by migueldeicaza** [comment]
I agree that this should be a class - otherwise we end up with even more complicated scenarios later involving copying.

**Comment by dsyme** [comment]
Yes, thanks.

**Comment by interesaaat** [comment]
In the initial implementation `TorchTensor` was a class but the performance were not that good: like training of MNIST and AlexNet was between 2 and 10x slower than the python implementation (I don't remember the exact number, this was more than 1 year ago). The result is this half-baked version with `struct`.

**Comment by dsyme** [comment]
> In the initial implementation TorchTensor was a class but the performance were not that good: like training of MNIST and AlexNet was between 2 and 10x slower than the python implementation (I don't remember the exact number, this was more than 1 year ago). The result is this half-baked version with struct.

I see, thanks. That's really an incredibly large difference, that's very curious.  Do you know if it was 

1. the costs of the .NET object allocations and their collection, or
2. the lack of deterministic free'ing of the C++ Tensors mucking up some kind of pooling inside LibTorch
3. something else

I'd be curious about the average size of the tensors in these cases too.

If this is indeed re-confirmed then a `TorchTensorImpl` or `TorchValueTensor` will indeed be necessary. I think it has to be for advanced high-performance uses however.

**Comment by interesaaat** [comment]
I believe that it was related to point 1. The tensor sizes we tested were the ones used in the MNIST and AlexNet example: I believe we used input mages of 28x28 and 32x32 (so yes, small images). But on the other side, if you use large images this won't probably not appear, but it will again for GPU.

**Comment by dsyme** [comment]
Hmmm interesting and challenging. With no batching?

**Comment by dsyme** [comment]
Closing as this is now a class, and we can add a `TorchTensorImpl` struct later

**Comment by interesaaat** [comment]
I think that for the experiment we used the batch size that is in the examples: 64.

**Comment by dsyme** [comment]
OK, thanks.

Feels odd if a single allocation for Tensor dominated over operations on tensors of size 32x32x64 - I'd need to dig into this.  I might do it in the context of DiffSharp where we have additional allocations over TorchTensor

DiffSharp could utilise a `TorchValueTensor` but we'd have to be really, really careful about it. I counted about 20 places where we were assuming `TorchTensor` were values that could be copied and duplicated around (which they now can be as a class)

**Comment by migueldeicaza** [comment]
I agree this would need some investigation, something else might have been going on at the time that exacerbated the problem.
