### ISSUE TITLE
Explicit load of some native DLLs needed on Windows to enable CUDA 

### ISSUE THREAD

**Issue by laizewei** [xamarin/TorchSharp#159]
.net core3.1.0  | win10 x64 | visual studio 16.6.0 Preview 6.0 | cuda 10.2
System.InvalidOperationException:“CUDA non available in the current machine.”
CPU mode is fine.
```csharp
------------------------------------------------
using System;
using System.IO;
using System.Linq;
using System.Numerics;
using System.Runtime.InteropServices;
using TorchSharp.Tensor;
using TorchSharp.NN;
using static TorchSharp.NN.Modules;
using static TorchSharp.NN.Losses;
using static TorchSharp.NN.Functions;

namespace ConsoleApp2
{
    class Program
    {
        static void Main(string[] args)
        {
            var shape = new long[] { 2, 2 };
            TorchTensor t = FloatTensor.Ones(shape,"cuda");  
             // TorchTensor t = FloatTensor.Ones(shape,"cpu");  //OK.
            Console.WriteLine(TorchSharp.Torch.IsCudaAvailable());
        }
    }
}
```

**Comment by dsyme** [comment]
What machine did you use?  Which runtime did you reference?

**Comment by laizewei** [comment]
GTX 1060 3GB | .NET Core 3.0 Runtime (EOL), | .NET Core 3.1 LTS runtime 
I have no problem running libtorch c++ code

**Comment by laizewei** [comment]
System.InvalidOperationException
  HResult=0x80131509
  Message=CUDA non available in the current machine.
  Source=TorchSharp
  StackTrace:
   at TorchSharp.Tensor.TorchTensor.CheckForCUDA(String device)
   at TorchSharp.Tensor.FloatTensor.Ones(Int64[] size, String device, Boolean requiresGrad)
   at ConsoleApp2.Program.Main(String[] args) in C:\Users\Administrator\source\repos\ConsoleApp2\ConsoleApp2\Program.cs:line 20

**Comment by dsyme** [comment]
Please share a whole project ZIP?

**Comment by laizewei** [comment]
My NUPKG Program source is in C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\ torchSharp \
libtorch-cuda-10.2-win-x64.1.5.6.nupkg
libtorch-cuda-10.2-win-x64-part1-fragment1.1.5.6.nupkg
libtorch-cuda-10.2-win-x64-part1-primary.1.5.6.nupkg
libtorch-cuda-10.2-win-x64-part2.1.5.6.nupkg
libtorch-cuda-10.2-win-x64-part3.1.5.6.nupkg
libtorch-cuda-10.2-win-x64-part4.0.3.52215.nupkg
libtorch-cuda-10.2-win-x64-part4-fragment1.1.5.6.nupkg
libtorch-cuda-10.2-win-x64-part4-primary.1.5.6.nupkg
libtorch-cuda-10.2-win-x64-part5.1.5.6.nupkg
torchsharp.0.3.52253.nupkg
torchsharp.symbols.0.3.52215.nupkg

**Comment by dsyme** [comment]
> Please share a whole project ZIP?

Please, a whole ZIP of cleaned project so we can see project file etc. and try to repro

**Comment by laizewei** [comment]
https://share.weiyun.com/8dAUXpvr
This is the ZIP link.

**Comment by dsyme** [comment]
@laizewei Hey I can't download those without a Weichat login.

Can you just push to github and send a link?

Or just past the contents of ConsoleApp2.csproj.

Also make sure you have a nuget package reference to either `libtorch-cuda-10.2` or `libtorch-cpu`.

**Comment by laizewei** [comment]
https://github.com/laizewei/errorzip 
This is the ZIP link.

**Comment by dsyme** [comment]
OK, I don't have a solution for this. Here are some ideas:

1. Your project file was a bit weird, try just using this.  I've unlisted the package you had with the strange version number
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="libtorch-cuda-10.2-win-x64" Version="1.5.6" />
    <PackageReference Include="TorchSharp" Version="0.3.52253" />
  </ItemGroup>

</Project>
```

2. When you say `I have no problem running libtorch c++ code` is this also using precisely LibTorch 1.5.0 for Cuda 10.2?  Is there anything special you have to do to get that to work - any environment variables, strange device names in strings or anything else?

**Comment by laizewei** [comment]
C++ Additional dependency:
c10.lib
c10_cuda.lib
asmjit.lib
caffe2_detectron_ops_gpu.lib
caffe2_module_test_dynamic.lib
caffe2_nvrtc.lib
clog.lib
cpuinfo.lib
fbgemm.lib
libprotobuf.lib
libprotobuf-lite.lib
libprotoc.lib
mkldnn.lib
torch.lib
torch_cpu.lib
torch_cuda.lib
-INCLUDE:?warp_size@cuda@at@@YAHXZ
C:\Program Files\NVIDIA Corporation\NvToolsExt\lib\x64\nvToolsExt64_1.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cudart_static.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cufft.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\curand.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cublas.lib
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib\x64\cudnn.lib
--------------------------------------
This is necessary:
-INCLUDE:?warp_size@cuda@at@@YAHXZ

**Comment by dsyme** [comment]
Hi there

I believe I've determined the problem, and CUDA tests are now passing on my machine 

The problem on Windows is this one https://github.com/pytorch/pytorch/issues/33415.  The workaround is to make an explicit an explicit call to `LoadLibrary("torch_cuda.dll")` before anything else.

I tested the CUDA testing https://github.com/xamarin/TorchSharp/pull/162 using:

* NVIDIA CUDA 10.2 SDK installed
* single NVIDIA GeForce RTX 2080 Ti card (also being used as display adaptor)

and all tests pass.

You can either apply the workaround manually or wait for an update.

**Comment by laizewei** [comment]
Thank you!

**Comment by dsyme** [comment]
Reopening this as there are still cases where the explicit load of `torch_cuda.dll` is not enough to resolve the problem.

This is particularly when the native binaries are placed in "runtimes/..." in the .NET Core application

Inside a `netcoreapp3.0` this is sufficent, however this API is currently only available in `netcoreapp3.0` and not in `netstandard3.0`.    Perhaps it's best to retarget TorchSharp to `netcoreapp3.0` for now to make these calls, since they appear necessary on Windows unfortunately 

```
        let mutable res = Unchecked.defaultof<_>
        let loaded1 = System.Runtime.InteropServices.NativeLibrary.TryLoad("torch_cuda", typeof<TorchSharp.Torch>.Assembly, System.Nullable(), &res) 
        let loaded2 = System.Runtime.InteropServices.NativeLibrary.TryLoad("nvrtc-builtins64_102", typeof<TorchSharp.Torch>.Assembly, System.Nullable(), &res) 
        let loaded3 = System.Runtime.InteropServices.NativeLibrary.TryLoad("caffe2_nvrtc", typeof<TorchSharp.Torch>.Assembly, System.Nullable(), &res) 
        let loaded4 = System.Runtime.InteropServices.NativeLibrary.TryLoad("nvrtc64_102_0", typeof<TorchSharp.Torch>.Assembly, System.Nullable(), &res) 
```
