### ISSUE TITLE
Slicing and indexing

### ISSUE THREAD

**Issue by AndersGarpebring** [xamarin/TorchSharp#166]
I'm looking for a tensor library that can do slicing and indexing. The c++ libtorch can do that very well but I see that it is not included in this package. Would it be possible to add? I tried to do it my self but for some reason the torch::indexing namespace is missing. Is it some old version of libtorch that is used in torchsharp so this namespace is missing?

**Comment by dsyme** [comment]
We have not needed that namespace yet - indeed I will take a look as it may be of use in DiffSharp (the main library using this package at the moment)

**Comment by dsyme** [comment]
(DiffSharp implements slicing and indexing but through its own code iteratively reducing to Torch's Squeeze and IndexSelect

https://github.com/DiffSharp/DiffSharp/blob/dev/src/DiffSharp.Backends.Torch/Torch.RawTensor.fs#L98)

**Comment by dsyme** [comment]
cc @gbaydin

**Comment by dsyme** [comment]
@AndersGarpebring You're welcome to contribute this support, it would be a great addition

**Comment by AndersGarpebring** [comment]
Thank you for the fast response. I've looked around a bit and it seems like the slicing functionality that I was looking for was introduced in libtorch around version 1.4. Torchsharp is using version 1.1. Are there any plans to update the version used?

**Comment by AndersGarpebring** [comment]
Btw what is the idea behind the memory management? Should I always call dispose when done with a tensor. If I run this code I had expected the GC to take care of memory management but I get out of memory (if n is large).

`using System;
using TorchSharp.Tensor;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            int n = 10;
            for (int i = 0; i< n; i++)
            {
                var x = FloatTensor.RandomN (new long[] { 64000, 1000 }, device: "cpu:0");
                //var y = x + 1.0;
                //var x = new long[64_000_000];
            }
            Console.WriteLine("Hello World!");
            Console.ReadKey ();
        }
    }
}`

**Comment by gbaydin** [comment]
> @dsyme Thank you for the fast response. I've looked around a bit and it seems like the slicing functionality that I was looking for was introduced in libtorch around version 1.4. Torchsharp is using version 1.1. Are there any plans to update the version used?

@AndersGarpebring as far as I know TorchSharp is currently based on libtorch 1.5.0. You can see this in the readme https://github.com/xamarin/TorchSharp/blob/master/README.md and libtorch nuget packages https://www.nuget.org/packages/libtorch-cpu/

**Comment by AndersGarpebring** [comment]
@gbaydin I downloaded the version from here and then it contains some code I interpreted as version 1.1. And indeed it is missing files that are available in 1.5.

The include path I found was:
...\GitHub\TorchSharp\bin\obj\AnyCPU.Debug\LibTorch.Redist\libtorch-win-shared-with-deps-1.1.0\libtorch\include

**Comment by AndersGarpebring** [comment]
I found the issue with version 1.1. I had an old fork on my system that I had forgotten about. In the later version the indexing methods are available in libtorch.

**Comment by dsyme** [comment]
OK, thanks, closing this issue
