### ISSUE TITLE
How to manage memory?

### ISSUE THREAD

**Issue by AndersGarpebring** [xamarin/TorchSharp#167]
What is the idea behind the memory management? Should I always call dispose when done with a tensor. If I run this code I had expected the GC to take care of memory management but I get out of memory (if n is large).

```
using System;
using TorchSharp.Tensor;

namespace ConsoleApp1
{
class Program
{
static void Main(string[] args)
{
int n = 10;
for (int i = 0; i< n; i++)
{
var x = FloatTensor.RandomN (new long[] { 64000, 1000 }, device: "cpu:0");
//var y = x + 1.0;
//var x = new long[64_000_000];
}
Console.WriteLine("Hello World!");
Console.ReadKey ();
}
}
}
```

**Comment by dsyme** [comment]
It could be we need to add a call to this for each allocation of a tensor (especially large ones, obviously)

https://docs.microsoft.com/en-us/dotnet/api/system.gc.addmemorypressure?view=netcore-3.1

**Comment by dsyme** [comment]
To answer the question - you can explicitly dispose, but if you don't then finalizers will be used.

(Note to self, from the docs: https://docs.microsoft.com/en-us/dotnet/api/system.gc.addmemorypressure?view=netcore-3.1

> The AddMemoryPressure and RemoveMemoryPressure methods improve performance only for types that exclusively depend on finalizers to release the unmanaged resources. It's not necessary to use these methods in types that follow the dispose pattern, where finalizers are used to clean up unmanaged resources only in the event that a consumer of the type forgets to call Dispose. For more information on object finalization and the dispose pattern, see Cleaning Up Unmanaged Resources.
)

**Comment by dsyme** [comment]
@AndersGarpebring #168 adds an option for registering native large tensors as causing memory pressure.  It is still explicit - and you must certainly make sure you're not holding on to tensors - but it helps the .NET GC be much more accurate about when to dispose the small object handles that wrap large native tensors.

**Comment by dsyme** [comment]
#168 also added docs on memory management here: https://github.com/xamarin/TorchSharp/blob/master/docfx/articles/memory.md so I'll close this for now
