### ISSUE TITLE
Ponder: Tensor type?

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/TorchSharp#18]
Perhaps there should be a `TorchSharp.Tensor` type that proxies to the right storage tensor, with an abstract interface, so that people can write generic-ish code that deals with Tensors, rather than having different data types.

Bonus points - even better would be to have the `Tensor` not surface a `Tensor<T>`, as that would defeat the reusability at that point.   This would have the downside that operations would have to dynamically check for type compatibility.

**Comment by dsyme** [comment]
We can close this, as there is a TorchTensor type?

**Comment by interesaaat** [comment]
I think that this issue was about adding generics to the `Tensor` type. I tried and failed miserably. I think we can close this if we think that generics are not necessary.

**Comment by migueldeicaza** [comment]
The work on @PartyDonk could have helped.
