### ISSUE TITLE
Summary of TorchSharp API that has yet to be implemented

### ISSUE THREAD

**Issue by GeorgeS2019** [xamarin/TorchSharp#193]
For Tensorflow.NET, finally we have [one page attempting to summarize what have yet to be implemented](https://github.com/SciSharp/tensorflow-net-docs/blob/master/docs/api/tf.md)

We need that for TorchSharp, which APIs have been implemented and Unit Tests written.

**Comment by dsyme** [comment]
That would be great

**Comment by GeorgeS2019** [comment]
Many of the [new issues at Tensorflow.NET ](https://github.com/SciSharp/TensorFlow.NET/issues/691)involve questions if something implemented yet.
Soon, when more and more adoption happens to TorchSharp, the same trend of questions will appear very soon.

**Comment by GeorgeS2019** [comment]
@dsyme we also discussed [the need of a repository](https://github.com/SciSharp/TensorFlow.NET/issues/618#issuecomment-700037288) focusing on proposals how to improve

**Comment by GeorgeS2019** [comment]
@dsyme  thank you for pushing TorchSharp. The .NET community need this and ideally the final goal will be one that user can copy and paste a pytorch python code and the output is TorchSharp c# working code.

Even if we just start with a basic example of this ambitious goal, this will inspire many to fill up the missing APIs.

**Comment by dsyme** [comment]
@GeorgeS2019 I totally agree F#/C# need this.

My main personal involvement is as a basis for DiffSharp, which has added tooling and differentiation capabilities.

**Comment by GeorgeS2019** [comment]
@dsyme I understand. However, you have laid down a STABLE and RELIABLE foundation upon which others can start lobby others to join your effort.

A few months perhaps to A year ago, I could not **easily** just git clone the repository and get the project compiled. Now, it is possible. A new beginning.

**Comment by dsyme** [comment]
@GeorgeS2019 If you'd like to become a co-admin that may be possible (I'm checking rules for Xamarin repos).  Certainly I'd encourage you to start taking a leading role in contributing to the project if you like its direction and want to use it

BTW I'll likely do a complete renaming to pythonesque naming to match Tensorflow.NET at some point - I see them very much as partner technologies.

**Comment by GeorgeS2019** [comment]
@dsyme  I know key people at Xamarin and I will keep pushing .NET machines language framework initiatives like TorchSharp etc. 

We just need a working strategy.

Now is the perfect time to make what could be better to RIGHT now

Everything right is happening e.g. .NET6 eventually

We just need to inspire more developers to join

You have laid down a good foundation.  We need to push both fronts, tensorflow.NET and TorchSharp.  We have made so much progress since a few years back when TensorflowSharp project was first created.

> I'll likely do a complete renaming to pythonesque naming to match Tensorflow.NET at some point 
We will lobby the community to MAKE THAT HAPPEN

The Tensorflow.NET received significant "love" from real PINVOKE expert from Microsoft, there are so many revisions on how to write efficient API to make tensorflow.NET OUT PERFORM tensorflow python in WINDOW OS, a major use case why .NET developers need to move into Tensorflow.NET

Tensorflow.NET was featured in one of .NET Monthly ML community session at Youtube.
TorchSharp deserve the same attention.  We just need to START getting there.

**Comment by dsyme** [comment]
> > I'll likely do a complete renaming to pythonesque naming to match Tensorflow.NET at some point

> We will lobby the community to MAKE THAT HAPPENS

No lobbying needed, we can just make that change here it's ok

**Comment by dsyme** [comment]
> The Tensorflow.NET received significant "love" from real PINVOKE expert from Microsoft, there are so many revisions on how to write efficient API to make tensorflow.NET OUT PERFORM tensorflow python in WINDOW OS, a major use case why .NET developers need to move into Tensorflow.NET

@GeorgeS2019 Do you have any links to that specific work?  I'd like to understand it as we may be able to reuse similar techniques here
