### ISSUE TITLE
Installation error by NuGet VS2015

### ISSUE THREAD

**Issue by Seven-year-promise** [xamarin/TorchSharp#194]
Could anyone help me with the installation?

I tried to install it by NuGet VS2015, but with following error:

"Could not install package 'TorchSharp 0.3.52363'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I am stopped by this step for days.

Thanks

**Comment by dsyme** [comment]
Use VS 2019

**Comment by Seven-year-promise** [comment]
thanks so much for your help
