### ISSUE TITLE
Missing Embedding functionality for language models

### ISSUE THREAD

**Issue by pkese** [xamarin/TorchSharp#216]
Several Pytorch examples like Word Language Model and Stanford Natural Language Inference Classifier require `torch.nn.Embedding` to be implemented:

https://github.com/pytorch/examples/blob/2c57b0011a096aef83da3b5265a14db2f80cb124/word_language_model/model.py#L13  
https://github.com/pytorch/examples/blob/2c57b0011a096aef83da3b5265a14db2f80cb124/snli/model.py#L43   
https://github.com/pytorch/examples/blob/5751edd199f20c17a366c0eed4932539b3697c18/distributed/rpc/rnn/rnn.py#L45

And I personally need it for training hierarchical models.

So I'm adding my wish for this to get included sometime.

**Comment by NiklasGustafsson** [comment]
Embedding was added in a recent PR, but has not made it to a NuGet release yet.

**Comment by NiklasGustafsson** [comment]
I take that back. It's in PR #217, so it's not in master yet..
