### ISSUE TITLE
Consider "torch.tensor(...)" and other such functions (through a lower-case `torch` type in `TorchSharp` namespace)

### ISSUE THREAD

**Issue by dsyme** [xamarin/TorchSharp#226]
The `Float32Tensor` in the tensor creation code currently looks a bit odd

    Float32Tensor.empty(new long[] { 64000, 1000 }, device: Device.CPU)

DiffSharp uses this sort of thing:

    dsharp.tensor([ 64000, 1000 ]) // F# tuples or lists accepted here 

    dsharp.randn(...) // the default is dtype=Dtype.Float32

It's quite possible we should simply align and support identical APIs or close enough to that:

    torch.tensor(new long[] { 64000, 1000 }, ...)

    torch.randn(...)

Note C#'s lack of a lightweight list literal syntax `[ .. ]` is a real problem for porting Python code. Tuples will help:

    torch.tensor(( 64000, 1000 ), ...)

but it will still be an intense experience of mindlessly replacing "[" with "(" etc. and the result is unfortunately less readable.

This requires creating a `torch` type like the [dsharp type](https://github.com/DiffSharp/DiffSharp/blob/dev/src/DiffSharp.Core/DiffSharp.fs#L12).  My judgment is in that the balance of concerns this is appropriate given the huge necessity to fluently move model and tensor code between PyTorch-Python, DiffSharp and TorchSharp

**Comment by pkese** [comment]
Why not just `torch.tensor`?

That would make the code much easier to port from Python.

**Comment by dsyme** [comment]
> Why not just torch.tensor?

Yes agreed

**Comment by NiklasGustafsson** [comment]
Addressed with PR #302
