### ISSUE TITLE
Binding: THFile API

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/TorchSharp#24]
- [x] THDiskFile_bigEndianEncoding
- [x] THDiskFile_isBigEndianCPU
- [x] THDiskFile_isLittleEndianCPU
- [x] THDiskFile_littleEndianEncoding
- [x] THDiskFile_longSize
- [x] THDiskFile_name
- [x] THDiskFile_nativeEndianEncoding
- [x] THDiskFile_new
- [x] THDiskFile_noBuffer
- [x] THFile_ascii
- [x] THFile_autoSpacing
- [x] THFile_binary
- [x] THFile_clearError
- [x] THFile_close
- [x] THFile_free
- [x] THFile_hasError
- [x] THFile_isAutoSpacing
- [x] THFile_isBinary
- [x] THFile_isOpened
- [x] THFile_isQuiet
- [x] THFile_isReadable
- [x] THFile_isWritable
- [x] THFile_noAutoSpacing
- [x] THFile_pedantic
- [x] THFile_position
- [x] THFile_quiet
- [x] THFile_readByte
- [x] THFile_readByteRaw
- [x] THFile_readByteScalar
- [x] THFile_readChar
- [x] THFile_readCharRaw
- [x] THFile_readCharScalar
- [x] THFile_readDouble
- [x] THFile_readDoubleRaw
- [x] THFile_readDoubleScalar
- [x] THFile_readFloat
- [x] THFile_readFloatRaw
- [x] THFile_readFloatScalar
- [ ] THFile_readHalf
- [ ] THFile_readHalfRaw
- [ ] THFile_readHalfScalar
- [x] THFile_readInt
- [x] THFile_readIntRaw
- [x] THFile_readIntScalar
- [x] THFile_readLong
- [x] THFile_readLongRaw
- [x] THFile_readLongScalar
- [x] THFile_readShort
- [x] THFile_readShortRaw
- [x] THFile_readShortScalar
- [ ] THFile_readStringRaw
- [x] THFile_seek
- [x] THFile_seekEnd
- [x] THFile_synchronize
- [x] THFile_writeByte
- [x] THFile_writeByteRaw
- [x] THFile_writeByteScalar
- [x] THFile_writeChar
- [x] THFile_writeCharRaw
- [x] THFile_writeCharScalar
- [x] THFile_writeDouble
- [x] THFile_writeDoubleRaw
- [x] THFile_writeDoubleScalar
- [x] THFile_writeFloat
- [x] THFile_writeFloatRaw
- [x] THFile_writeFloatScalar
- [ ] THFile_writeHalf
- [ ] THFile_writeHalfRaw
- [ ] THFile_writeHalfScalar
- [x] THFile_writeInt
- [x] THFile_writeIntRaw
- [x] THFile_writeIntScalar
- [x] THFile_writeLong
- [x] THFile_writeLongRaw
- [x] THFile_writeLongScalar
- [x] THFile_writeShort
- [x] THFile_writeShortRaw
- [x] THFile_writeShortScalar
- [x] THFile_writeStringRaw
- [x] THMemoryFile_longSize
- [x] THMemoryFile_new
- [x] THMemoryFile_newWithStorage
- [x] THMemoryFile_storage
- [x] THPipeFile_new

**Comment by NiklasGustafsson** [comment]
I'll pick this one up.

**Comment by dsyme** [comment]
Closing as this is ATen specific https://github.com/xamarin/TorchSharp/pull/129
