### ISSUE TITLE
Consistency across Torch API binding

### ISSUE THREAD

**Issue by GeorgeS2019** [xamarin/TorchSharp#249]
All binding e.g. Rust, Go and others ( I may be wrong), clearly have a folder dedicated to all neural network implementation.

Just by looking at the number of files under the neural network folder, one can immediately see what have been implemented and what are not.  Same for other Torch API folders 

For TorchSharp, all NN implementations are embedded within ONE SINGLE file.  This also makes versioning tracking which **individual** TorchSharp **NN implementation** not so straight forward.

This makes it not so straight forward **to track** what have been done and what have not been done.

Torch API development is moving at fast pace. Just like Tensorflow.NET, one of the biggest challenges will be to track what have not been done by just comparing the number of files per each folder instead of parsing through e.g. that single NN file to track the completeness of NN implementation.

All Toruch API binding adhere closely to the folder structure of Torch c API. I suggest eventually the TorchSharp follows the same to make tracking and a quick one glance what else is missing VERY CLEAR!

**Comment by GeorgeS2019** [comment]
There have been questions if a particular NN feature has been implemented in the past. This requires the one request to do that in C++ not C#.  The bottleneck is C++ and not C#.  The C# NN folder is consistent with other API binding implementation e.g. Rust, Go.  The C++ LibTorchSharp for NN is one single file [THSNN.cpp](https://github.com/xamarin/TorchSharp/blob/master/src/Native/LibTorchSharp/THSNN.cpp).  If we make this one c++ file to be split into multiple files.  When implementing new NN, it will feel less intimidating instead of managing ONE GIANT THSNN.cpp file.  Hopefully this will encourage regular contribution to c++, potentially the limiting step in keep up with the latest Torch development.

**Comment by GeorgeS2019** [comment]
- Request for [Automatic generation of the C API](https://github.com/xamarin/TorchSharp/issues/83)- [ 

- > I've been trying to[ **locate** ](https://github.com/xamarin/TorchSharp/issues/199#issue-814743022)the libtorch tensor indexing/slicing API in TorchSharp:

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- I don't see what the concrete ask is here, anymore. The C++ code has been split into multiple files. Please close this issue if you agree. If not, please add another comment with specific remaining asks.
