### ISSUE TITLE
Binding: THNN APIs

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/TorchSharp#25]
- [ ] THNN_DoubleAbsCriterion_updateGradInput
- [ ] THNN_DoubleAbsCriterion_updateOutput
- [ ] THNN_DoubleBCECriterion_updateGradInput
- [ ] THNN_DoubleBCECriterion_updateOutput
- [ ] THNN_DoubleBatchNormalization_backward
- [ ] THNN_DoubleBatchNormalization_updateOutput
- [ ] THNN_DoubleClassNLLCriterion_updateGradInput
- [ ] THNN_DoubleClassNLLCriterion_updateOutput
- [ ] THNN_DoubleCol2Im_updateGradInput
- [ ] THNN_DoubleCol2Im_updateOutput
- [ ] THNN_DoubleELU_updateGradInput
- [ ] THNN_DoubleELU_updateOutput
- [ ] THNN_DoubleFeatureLPPooling_updateGradInput
- [ ] THNN_DoubleFeatureLPPooling_updateOutput
- [ ] THNN_DoubleGatedLinear_updateGradInput
- [ ] THNN_DoubleGatedLinear_updateOutput
- [ ] THNN_DoubleHardTanh_updateGradInput
- [ ] THNN_DoubleHardTanh_updateOutput
- [ ] THNN_DoubleIm2Col_updateGradInput
- [ ] THNN_DoubleIm2Col_updateOutput
- [ ] THNN_DoubleIndexLinear_accGradParameters
- [ ] THNN_DoubleIndexLinear_accUpdateGradParameters
- [ ] THNN_DoubleIndexLinear_updateOutput
- [ ] THNN_DoubleIndexLinear_updateParameters
- [ ] THNN_DoubleLeakyReLU_updateGradInput
- [ ] THNN_DoubleLeakyReLU_updateOutput
- [ ] THNN_DoubleLogSigmoid_updateGradInput
- [ ] THNN_DoubleLogSigmoid_updateOutput
- [ ] THNN_DoubleMSECriterion_updateGradInput
- [ ] THNN_DoubleMSECriterion_updateOutput
- [ ] THNN_DoubleMultiLabelMarginCriterion_updateGradInput
- [ ] THNN_DoubleMultiLabelMarginCriterion_updateOutput
- [ ] THNN_DoubleMultiMarginCriterion_updateGradInput
- [ ] THNN_DoubleMultiMarginCriterion_updateOutput
- [ ] THNN_DoubleRReLU_updateGradInput
- [ ] THNN_DoubleRReLU_updateOutput
- [ ] THNN_DoubleSigmoid_updateGradInput
- [ ] THNN_DoubleSigmoid_updateOutput
- [ ] THNN_DoubleSmoothL1Criterion_updateGradInput
- [ ] THNN_DoubleSmoothL1Criterion_updateOutput
- [ ] THNN_DoubleSoftMarginCriterion_updateGradInput
- [ ] THNN_DoubleSoftMarginCriterion_updateOutput
- [ ] THNN_DoubleSoftPlus_updateGradInput
- [ ] THNN_DoubleSoftPlus_updateOutput
- [ ] THNN_DoubleSoftShrink_updateGradInput
- [ ] THNN_DoubleSoftShrink_updateOutput
- [ ] THNN_DoubleSparseLinear_accGradParameters
- [ ] THNN_DoubleSparseLinear_legacyAccGradParameters
- [ ] THNN_DoubleSparseLinear_legacyUpdateOutput
- [ ] THNN_DoubleSparseLinear_legacyUpdateParameters
- [ ] THNN_DoubleSparseLinear_legacyZeroGradParameters
- [ ] THNN_DoubleSparseLinear_updateOutput
- [ ] THNN_DoubleSparseLinear_updateParameters
- [ ] THNN_DoubleSparseLinear_zeroGradParameters
- [ ] THNN_DoubleSpatialAdaptiveAveragePooling_updateGradInput
- [ ] THNN_DoubleSpatialAdaptiveAveragePooling_updateOutput
- [ ] THNN_DoubleSpatialAdaptiveMaxPooling_updateGradInput
- [ ] THNN_DoubleSpatialAdaptiveMaxPooling_updateOutput
- [ ] THNN_DoubleSpatialAveragePooling_updateGradInput
- [ ] THNN_DoubleSpatialAveragePooling_updateOutput
- [ ] THNN_DoubleSpatialClassNLLCriterion_updateGradInput
- [ ] THNN_DoubleSpatialClassNLLCriterion_updateOutput
- [ ] THNN_DoubleSpatialConvolutionMM_accGradParameters
- [ ] THNN_DoubleSpatialConvolutionMM_updateGradInput
- [ ] THNN_DoubleSpatialConvolutionMM_updateOutput
- [ ] THNN_DoubleSpatialDilatedConvolution_accGradParameters
- [ ] THNN_DoubleSpatialDilatedConvolution_updateGradInput
- [ ] THNN_DoubleSpatialDilatedConvolution_updateOutput
- [ ] THNN_DoubleSpatialDilatedMaxPooling_updateGradInput
- [ ] THNN_DoubleSpatialDilatedMaxPooling_updateOutput
- [ ] THNN_DoubleSpatialFractionalMaxPooling_updateGradInput
- [ ] THNN_DoubleSpatialFractionalMaxPooling_updateOutput
- [ ] THNN_DoubleSpatialFullDilatedConvolution_accGradParameters
- [ ] THNN_DoubleSpatialFullDilatedConvolution_updateGradInput
- [ ] THNN_DoubleSpatialFullDilatedConvolution_updateOutput
- [ ] THNN_DoubleSpatialMaxUnpooling_updateGradInput
- [ ] THNN_DoubleSpatialMaxUnpooling_updateOutput
- [ ] THNN_DoubleSpatialReflectionPadding_updateGradInput
- [ ] THNN_DoubleSpatialReflectionPadding_updateOutput
- [ ] THNN_DoubleSpatialReplicationPadding_updateGradInput
- [ ] THNN_DoubleSpatialReplicationPadding_updateOutput
- [ ] THNN_DoubleSpatialUpSamplingBilinear_updateGradInput
- [ ] THNN_DoubleSpatialUpSamplingBilinear_updateOutput
- [ ] THNN_DoubleSpatialUpSamplingNearest_updateGradInput
- [ ] THNN_DoubleSpatialUpSamplingNearest_updateOutput
- [ ] THNN_DoubleTanh_updateGradInput
- [ ] THNN_DoubleTanh_updateOutput
- [ ] THNN_DoubleTemporalReflectionPadding_updateGradInput
- [ ] THNN_DoubleTemporalReflectionPadding_updateOutput
- [ ] THNN_DoubleTemporalReplicationPadding_updateGradInput
- [ ] THNN_DoubleTemporalReplicationPadding_updateOutput
- [ ] THNN_DoubleTemporalRowConvolution_accGradParameters
- [ ] THNN_DoubleTemporalRowConvolution_updateGradInput
- [ ] THNN_DoubleTemporalRowConvolution_updateOutput
- [ ] THNN_DoubleTemporalUpSamplingLinear_updateGradInput
- [ ] THNN_DoubleTemporalUpSamplingLinear_updateOutput
- [ ] THNN_DoubleTemporalUpSamplingNearest_updateGradInput
- [ ] THNN_DoubleTemporalUpSamplingNearest_updateOutput
- [ ] THNN_DoubleThreshold_updateGradInput
- [ ] THNN_DoubleThreshold_updateOutput
- [ ] THNN_DoubleVolumetricAdaptiveAveragePooling_updateGradInput
- [ ] THNN_DoubleVolumetricAdaptiveAveragePooling_updateOutput
- [ ] THNN_DoubleVolumetricAdaptiveMaxPooling_updateGradInput
- [ ] THNN_DoubleVolumetricAdaptiveMaxPooling_updateOutput
- [ ] THNN_DoubleVolumetricAveragePooling_updateGradInput
- [ ] THNN_DoubleVolumetricAveragePooling_updateOutput
- [ ] THNN_DoubleVolumetricConvolutionMM_accGradParameters
- [ ] THNN_DoubleVolumetricConvolutionMM_updateGradInput
- [ ] THNN_DoubleVolumetricConvolutionMM_updateOutput
- [ ] THNN_DoubleVolumetricDilatedConvolution_accGradParameters
- [ ] THNN_DoubleVolumetricDilatedConvolution_updateGradInput
- [ ] THNN_DoubleVolumetricDilatedConvolution_updateOutput
- [ ] THNN_DoubleVolumetricDilatedMaxPooling_updateGradInput
- [ ] THNN_DoubleVolumetricDilatedMaxPooling_updateOutput
- [ ] THNN_DoubleVolumetricFullDilatedConvolution_accGradParameters
- [ ] THNN_DoubleVolumetricFullDilatedConvolution_updateGradInput
- [ ] THNN_DoubleVolumetricFullDilatedConvolution_updateOutput
- [ ] THNN_DoubleVolumetricMaxUnpooling_updateGradInput
- [ ] THNN_DoubleVolumetricMaxUnpooling_updateOutput
- [ ] THNN_DoubleVolumetricReplicationPadding_updateGradInput
- [ ] THNN_DoubleVolumetricReplicationPadding_updateOutput
- [ ] THNN_DoubleVolumetricUpSamplingNearest_updateGradInput
- [ ] THNN_DoubleVolumetricUpSamplingNearest_updateOutput
- [ ] THNN_DoubleVolumetricUpSamplingTrilinear_updateGradInput
- [ ] THNN_DoubleVolumetricUpSamplingTrilinear_updateOutput
- [ ] THNN_Doubleunfolded_acc
- [ ] THNN_Doubleunfolded_copy
- [ ] THNN_FloatAbsCriterion_updateGradInput
- [ ] THNN_FloatAbsCriterion_updateOutput
- [ ] THNN_FloatBCECriterion_updateGradInput
- [ ] THNN_FloatBCECriterion_updateOutput
- [ ] THNN_FloatBatchNormalization_backward
- [ ] THNN_FloatBatchNormalization_updateOutput
- [ ] THNN_FloatClassNLLCriterion_updateGradInput
- [ ] THNN_FloatClassNLLCriterion_updateOutput
- [ ] THNN_FloatCol2Im_updateGradInput
- [ ] THNN_FloatCol2Im_updateOutput
- [ ] THNN_FloatELU_updateGradInput
- [ ] THNN_FloatELU_updateOutput
- [ ] THNN_FloatFeatureLPPooling_updateGradInput
- [ ] THNN_FloatFeatureLPPooling_updateOutput
- [ ] THNN_FloatGatedLinear_updateGradInput
- [ ] THNN_FloatGatedLinear_updateOutput
- [ ] THNN_FloatHardTanh_updateGradInput
- [ ] THNN_FloatHardTanh_updateOutput
- [ ] THNN_FloatIm2Col_updateGradInput
- [ ] THNN_FloatIm2Col_updateOutput
- [ ] THNN_FloatIndexLinear_accGradParameters
- [ ] THNN_FloatIndexLinear_accUpdateGradParameters
- [ ] THNN_FloatIndexLinear_updateOutput
- [ ] THNN_FloatIndexLinear_updateParameters
- [ ] THNN_FloatLeakyReLU_updateGradInput
- [ ] THNN_FloatLeakyReLU_updateOutput
- [ ] THNN_FloatLogSigmoid_updateGradInput
- [ ] THNN_FloatLogSigmoid_updateOutput
- [ ] THNN_FloatMSECriterion_updateGradInput
- [ ] THNN_FloatMSECriterion_updateOutput
- [ ] THNN_FloatMultiLabelMarginCriterion_updateGradInput
- [ ] THNN_FloatMultiLabelMarginCriterion_updateOutput
- [ ] THNN_FloatMultiMarginCriterion_updateGradInput
- [ ] THNN_FloatMultiMarginCriterion_updateOutput
- [ ] THNN_FloatRReLU_updateGradInput
- [ ] THNN_FloatRReLU_updateOutput
- [ ] THNN_FloatSigmoid_updateGradInput
- [ ] THNN_FloatSigmoid_updateOutput
- [ ] THNN_FloatSmoothL1Criterion_updateGradInput
- [ ] THNN_FloatSmoothL1Criterion_updateOutput
- [ ] THNN_FloatSoftMarginCriterion_updateGradInput
- [ ] THNN_FloatSoftMarginCriterion_updateOutput
- [ ] THNN_FloatSoftPlus_updateGradInput
- [ ] THNN_FloatSoftPlus_updateOutput
- [ ] THNN_FloatSoftShrink_updateGradInput
- [ ] THNN_FloatSoftShrink_updateOutput
- [ ] THNN_FloatSparseLinear_accGradParameters
- [ ] THNN_FloatSparseLinear_legacyAccGradParameters
- [ ] THNN_FloatSparseLinear_legacyUpdateOutput
- [ ] THNN_FloatSparseLinear_legacyUpdateParameters
- [ ] THNN_FloatSparseLinear_legacyZeroGradParameters
- [ ] THNN_FloatSparseLinear_updateOutput
- [ ] THNN_FloatSparseLinear_updateParameters
- [ ] THNN_FloatSparseLinear_zeroGradParameters
- [ ] THNN_FloatSpatialAdaptiveAveragePooling_updateGradInput
- [ ] THNN_FloatSpatialAdaptiveAveragePooling_updateOutput
- [ ] THNN_FloatSpatialAdaptiveMaxPooling_updateGradInput
- [ ] THNN_FloatSpatialAdaptiveMaxPooling_updateOutput
- [ ] THNN_FloatSpatialAveragePooling_updateGradInput
- [ ] THNN_FloatSpatialAveragePooling_updateOutput
- [ ] THNN_FloatSpatialClassNLLCriterion_updateGradInput
- [ ] THNN_FloatSpatialClassNLLCriterion_updateOutput
- [ ] THNN_FloatSpatialConvolutionMM_accGradParameters
- [ ] THNN_FloatSpatialConvolutionMM_updateGradInput
- [ ] THNN_FloatSpatialConvolutionMM_updateOutput
- [ ] THNN_FloatSpatialDilatedConvolution_accGradParameters
- [ ] THNN_FloatSpatialDilatedConvolution_updateGradInput
- [ ] THNN_FloatSpatialDilatedConvolution_updateOutput
- [ ] THNN_FloatSpatialDilatedMaxPooling_updateGradInput
- [ ] THNN_FloatSpatialDilatedMaxPooling_updateOutput
- [ ] THNN_FloatSpatialFractionalMaxPooling_updateGradInput
- [ ] THNN_FloatSpatialFractionalMaxPooling_updateOutput
- [ ] THNN_FloatSpatialFullDilatedConvolution_accGradParameters
- [ ] THNN_FloatSpatialFullDilatedConvolution_updateGradInput
- [ ] THNN_FloatSpatialFullDilatedConvolution_updateOutput
- [ ] THNN_FloatSpatialMaxUnpooling_updateGradInput
- [ ] THNN_FloatSpatialMaxUnpooling_updateOutput
- [ ] THNN_FloatSpatialReflectionPadding_updateGradInput
- [ ] THNN_FloatSpatialReflectionPadding_updateOutput
- [ ] THNN_FloatSpatialReplicationPadding_updateGradInput
- [ ] THNN_FloatSpatialReplicationPadding_updateOutput
- [ ] THNN_FloatSpatialUpSamplingBilinear_updateGradInput
- [ ] THNN_FloatSpatialUpSamplingBilinear_updateOutput
- [ ] THNN_FloatSpatialUpSamplingNearest_updateGradInput
- [ ] THNN_FloatSpatialUpSamplingNearest_updateOutput
- [ ] THNN_FloatTanh_updateGradInput
- [ ] THNN_FloatTanh_updateOutput
- [ ] THNN_FloatTemporalReflectionPadding_updateGradInput
- [ ] THNN_FloatTemporalReflectionPadding_updateOutput
- [ ] THNN_FloatTemporalReplicationPadding_updateGradInput
- [ ] THNN_FloatTemporalReplicationPadding_updateOutput
- [ ] THNN_FloatTemporalRowConvolution_accGradParameters
- [ ] THNN_FloatTemporalRowConvolution_updateGradInput
- [ ] THNN_FloatTemporalRowConvolution_updateOutput
- [ ] THNN_FloatTemporalUpSamplingLinear_updateGradInput
- [ ] THNN_FloatTemporalUpSamplingLinear_updateOutput
- [ ] THNN_FloatTemporalUpSamplingNearest_updateGradInput
- [ ] THNN_FloatTemporalUpSamplingNearest_updateOutput
- [ ] THNN_FloatThreshold_updateGradInput
- [ ] THNN_FloatThreshold_updateOutput
- [ ] THNN_FloatVolumetricAdaptiveAveragePooling_updateGradInput
- [ ] THNN_FloatVolumetricAdaptiveAveragePooling_updateOutput
- [ ] THNN_FloatVolumetricAdaptiveMaxPooling_updateGradInput
- [ ] THNN_FloatVolumetricAdaptiveMaxPooling_updateOutput
- [ ] THNN_FloatVolumetricAveragePooling_updateGradInput
- [ ] THNN_FloatVolumetricAveragePooling_updateOutput
- [ ] THNN_FloatVolumetricConvolutionMM_accGradParameters
- [ ] THNN_FloatVolumetricConvolutionMM_updateGradInput
- [ ] THNN_FloatVolumetricConvolutionMM_updateOutput
- [ ] THNN_FloatVolumetricDilatedConvolution_accGradParameters
- [ ] THNN_FloatVolumetricDilatedConvolution_updateGradInput
- [ ] THNN_FloatVolumetricDilatedConvolution_updateOutput
- [ ] THNN_FloatVolumetricDilatedMaxPooling_updateGradInput
- [ ] THNN_FloatVolumetricDilatedMaxPooling_updateOutput
- [ ] THNN_FloatVolumetricFullDilatedConvolution_accGradParameters
- [ ] THNN_FloatVolumetricFullDilatedConvolution_updateGradInput
- [ ] THNN_FloatVolumetricFullDilatedConvolution_updateOutput
- [ ] THNN_FloatVolumetricMaxUnpooling_updateGradInput
- [ ] THNN_FloatVolumetricMaxUnpooling_updateOutput
- [ ] THNN_FloatVolumetricReplicationPadding_updateGradInput
- [ ] THNN_FloatVolumetricReplicationPadding_updateOutput
- [ ] THNN_FloatVolumetricUpSamplingNearest_updateGradInput
- [ ] THNN_FloatVolumetricUpSamplingNearest_updateOutput
- [ ] THNN_FloatVolumetricUpSamplingTrilinear_updateGradInput
- [ ] THNN_FloatVolumetricUpSamplingTrilinear_updateOutput
- [ ] THNN_Floatunfolded_acc
- [ ] THNN_Floatunfolded_copy

**Comment by migueldeicaza** [comment]
Does not look like this is a public API

**Comment by interesaaat** [comment]
@migueldeicaza I think we need these APIs to implement NN operators. How did you find that they are not public? Does this mean that we cannot access these APIs at all or that they are reachable through some other API?

**Comment by migueldeicaza** [comment]
Could not find the header files for these.

**Comment by migueldeicaza** [comment]
Ok found it - https://github.com/torch/nn/tree/master/lib/THNN

**Comment by migueldeicaza** [comment]
Researching how to bind this, challenges with THNNState

**Comment by migueldeicaza** [comment]
I am doing these ones.

**Comment by migueldeicaza** [comment]
Update from the discussion on gitter:

```
I wrote a tool to do the THNN binding
Now, the issue is, it feels like these operations belong on the Float/Double tensors
So good news - I have all the bits ready
Bad news - I think I need to play a little with the Lua/Python API to get a better sense of how this was intended to be used
Just does not feel right, but design wise, that is where it looks they belong
```

**Comment by migueldeicaza** [comment]
The binding is going into this pull request

https://github.com/xamarin/TorchSharp/pull/38

But it is intended to be internal, which is surfaced by individual classes later.
