### ISSUE TITLE
A question about parallel training / sharing gradients

### ISSUE THREAD

**Issue by pkese** [xamarin/TorchSharp#250]
One way to parallelize training is to extract just the gradients (without weights) from device A, copy them to device B and then add them to existing gradients on that device (B) before the optimizer step.

As far as I understand, gradients can be extracted using `tensor.grad()` as well as added together (producing a new gradient tensor),  
but is there any way to assign the sum of gradients back to the relevant tensor before the optimizer step?

**Comment by NiklasGustafsson** [comment]
@pkese, I would think that using 'copy_()' would allow you to copy the manipulated gradients back into the gradients tensor. Don't take my word for it, though,.

**Comment by pkese** [comment]
Sure.
I'm using a little bit different architecture now, so I can't try it now, but I think that yes, `copy_()` will fix the problem.
Thanks.
