### ISSUE TITLE
Saving / loading modules does not work

### ISSUE THREAD

**Issue by NiklasGustafsson** [xamarin/TorchSharp#251]
Saving, then loading a module, even simple things like linear layers, does not work. The loaded parameters are empty.

The existing unit tests did not actually check for anything significant being loaded, just that a C# object was being created.

Created this issue to track.

**Comment by NiklasGustafsson** [comment]
I'm trying to come up with a fix for this.

When I look at the [PyTorch docs](https://pytorch.org/tutorials/beginner/basics/saveloadrun_tutorial.html), the right way to save and load models is to pickle the ‘state_dict’ property of each model/module. Pickling is Python-specific, so I don’t expect there to be much chance of loading models that have been created using Python code.

My current thought is to define a .NET-specific format for saving the state_dict. Having an explicit and documented format means that we could also come up with a Python implementation, which means that the state_dict could be exported using the same format and then be readable from .NET.

**Comment by dsyme** [comment]
> When I look at the PyTorch docs, the right way to save and load models is to pickle the ‘state_dict’ property of each model/module. Pickling is Python-specific, so I don’t expect there to be much chance of loading models that have been created using Python code.

I think we should take a good look at re-implementing the load/save of the python format.  It's likely other systems (e.g. Rust?) have had to reimplement this

I think this is ultimately the place we would need to land.  At least we need to know whether it's possible

**Comment by NiklasGustafsson** [comment]
From a purist perspective, I absolutely agree. 

That said, the Python pickle format is intricate, closely tied to the Python object model, and subject to change. There have been breaking changes between versions. It would be a significant effort to write an unpickler for .NET.

On the other hand, to export the module state, a very simple serialization format is all that is required -- the most complex thing is using LEB128 encoding of string lengths, so that the .NET BinaryReader can load them. The Python code is about 45 lines of code (without comments).

**Comment by NiklasGustafsson** [comment]
Recent PRs have implemented a load/save mechanism that is unique to .NET, but includes a Python script to export (not import) from Python training. Therefore, I'll close this issue.

**Comment by FusionCarcass** [comment]
Can you show us an example of how to load a model exported from python? I cannot figure out how to do it. There seemed to be an example online that recommended using TorchSharp.JIT.Module.Load, but that entire file was commented out in the most recent release.

**Comment by NiklasGustafsson** [comment]
This article should have everything you need:

https://github.com/dotnet/TorchSharp/blob/main/docfx/articles/saveload.md
