### ISSUE TITLE
requesting support for tensor concatenation (torch.cat)

### ISSUE THREAD

**Issue by fwaris** [xamarin/TorchSharp#268]
torch.cat is an essential function for many models. It would be good to have support for tensor concatenation

**Comment by dsyme** [comment]
It is there, it's just really, really non-discoverable and should be redone as `torch.cat`

It's an extension method to `IList<Tensor>`, e.g. `arrayOfTensor.cat(dimension)`

https://github.com/xamarin/TorchSharp/blob/8adf8326b2eb998a0998d5b0235b8bb48b324a37/src/TorchSharp/Tensor/TensorExtensionMethods.cs#L172

**Comment by fwaris** [comment]
thanks for clarifying @dsyme. I agree something like torch.cat would be easier to find, especially if you are porting an existing model

**Comment by NiklasGustafsson** [comment]
With #302, 'torch.cat' is indeed where this function is to be found.
