### ISSUE TITLE
DLL loading issue

### ISSUE THREAD

**Issue by pkese** [xamarin/TorchSharp#269]
I have a following script:

```fsharp
#r "nuget: libtorch-cpu, 1.8.0.7"
#r "nuget: TorchSharp, 0.91.52604"

open TorchSharp

[<AutoOpen>]
module Helpers = 
    let inline fscalar x = TorchScalar.op_Implicit (float32 x)

let torch_pi = fscalar 3.14

printfn $"{torch_pi.ToDouble()}"
```

Without explicitly configured LD_LIBRARY_PATH I get
```bash
#> dotnet fsi test.fsx 
System.DllNotFoundException: Unable to load shared library 'LibTorchSharp' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libLibTorchSharp: cannot open shared object file: No such file or directory
   at TorchSharp.ScalarExtensionMethods.THSTorch_float32_to_scalar(Single value)
   at TorchSharp.ScalarExtensionMethods.ToScalar(Single value)
   at TorchSharp.TorchScalar.op_Implicit(Single value)
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
Stopped due to error
```

...but with explicit paths, it works as expected:
```bash
#> LD_LIBRARY_PATH=/home/peter/.nuget/packages/libtorch-cpu/1.8.0.7/runtimes/linux-x64/native/ dotnet fsi test.fsx 
3.140000104904175
```

**Comment by dsyme** [comment]
It looks like another manifestation of https://github.com/xamarin/TorchSharp/issues/169

There is some bespoke code in the TorchSharp initialization code to try to deal with this.  I think the initialization is not being forced by your code.  I'll take a look

**Comment by dsyme** [comment]
Yeah, we're only doing the InitializeDeviceType calls for CUDA, and not CPU, e.g. 

https://github.com/xamarin/TorchSharp/blob/2386aaa786fb76582665e31df6a38924ad24a670/src/TorchSharp/Tensor/TorchTensor.cs#L645

Could you see if making this call yourself in the script fixes things?

**Comment by dsyme** [comment]
@NiklasGustafsson Basically we should sprinkle calls to 

    Torch.InitializeDeviceType(deviceType);

before all tensor and scalar creation routines.  It is fast, it won't affect peformance.

**Comment by pkese** [comment]
Indeed `Torch.InitializeDeviceType(DeviceType.CPU)` fixes my problem.  
Thanks

**Comment by NiklasGustafsson** [comment]
That'll be a lot of places to add the call -- essentially every conversion, every factory. Can we be sure that it doesn't have a big impact in aggregate? Could we do it from a static class constructor?

**Comment by dsyme** [comment]
> That'll be a lot of places to add the call -- essentially every conversion, every factory. Can we be sure that it doesn't have a big impact in aggregate? 

Yes, I'm sure (at most a boolean check, we do that and more for error conditions on every call)

> Could we do it from a static class constructor?

Maybe

**Comment by pkese** [comment]
Don't we need those just on constructors?  
I'm assuming one can't do much tensor arithmetic before first creating tensors or scalars.

**Comment by dsyme** [comment]
> I'm assuming one can't do much tensor arithmetic before first creating tensors or scalars.

Yes that's right, things like `ones`, `zeros`, `arange` etc.

**Comment by pkese** [comment]
Yes. Sorry, I removed that comment because it didn't add anything new to discussion.  
Above, you already said: "before all tensor and scalar **creation** routines"

**Comment by NiklasGustafsson** [comment]
I've submitted a PR for the fix to this problem. Most factories already had the initialization logic, but ToScalar() and the from() variant that takes a list of .NET scalars did not.
