### ISSUE TITLE
dotnet build fails to generate TypeGeneration.cs on linux

### ISSUE THREAD

**Issue by motus** [xamarin/TorchSharp#27]
Since the removal of `TypeGeneration.cs` file in e1c83dfdb0c6b6cfd8d8655f22c77019b5b30787, I cannot build the project on Linux. Obviously, I don't have the VisualStudio to generate the file, and I cannot figure out if there is a combination of options to do it using only dotnet/msbuild. Here's what I get:

```text
motus@motus-xps13:~/devel/TorchSharp/Tester:master$ dotnet run
Program.cs(5,20): error CS0246: The type or namespace name 'FloatTensor' could not be found (are you missing a using directive or an assembly reference?) [/home/motus/devel/TorchSharp/Tester/Tester.csproj]

The build failed. Please fix the build errors and run again.
motus@motus-xps13:~/devel/TorchSharp/Tester:master$ dotnet --version
2.1.403
```
I think @NiklasGustafsson has the same problem. @migueldeicaza, do you know how to fix it? Thank you!

**Comment by NiklasGustafsson** [comment]
I got around this problem on my Mac by running the tool from within VS, but it seems to me that it should be run automatically when you do ‘dotnet build’ or at least ‘msbuild.’

Niklas

**Comment by markusweimer** [comment]
There is a whole [thread on this on reddit](https://www.reddit.com/r/dotnet/comments/4qolb0/netcore_and_t4_or_alternatives/). T4 is not part of .NET Core. The suggested alternative to use is [Scripty](https://github.com/daveaglick/Scripty).

**Comment by migueldeicaza** [comment]
I undid the removal of TypeGeneration.cs, for a similar reason, so for now it is checked in.

I am using VSMac for doing the build, on Linux, you can use MonoDevelop (which is basically Visual Studio for Mac without the mobile extensions).

**Comment by mhutch** [comment]
FWIW it's generally necessary to check in the output of tt files. This is because they follow the model of design-time generation (think winforms designer files) rather than the more modern build integrated generation used by e.g. xaml. It would be possible to change the generation model once an msbuild task existed, like in the issue I linked.

**Comment by migueldeicaza** [comment]
I am going to close the issue, given the comment above, but I would like longer term to make a build script that manually triggers the use of the Mono.TextTempalting NuGet.
