### ISSUE TITLE
Provide a Test Driven Development (TDD) TorchSharp repository

### ISSUE THREAD

**Issue by JimFFM** [xamarin/TorchSharp#287]
Provide a **separate** (test-driven development TorchSharp) **repository** with the provided codes from the directories
- TorchSharpTest and 
- TorchSharpTest.WithCudaBinaries 

the repository reference by project or nuget the latest TorchSharp.dll with the possibility to include the cpu or/and cuda libtorch packages

- package libtorch-cpu --version 1.9.0.1 OR
- package libtorch-cuda-11.1-win-x64 --version 1.9.0.1

Currently, I find the TorchSharp repository "coupled" to work ONLY through **command line**
- dotnet build
- dotnet test
- dotnet pack

I am not able to git clone the repository and then start **VS2019** to build, test and pack the repository

By having a "ready to work" TDD torchsharp repository, users can straight forwards try migrating pytorch codes to get them work with TorchSharp.

**Comment by GeorgeS2019** [comment]
The recent commits seems to solve the build, test from VS2019

**Comment by NiklasGustafsson** [comment]
@JimFFM -- I was about to respond, but I see that you closed the issue.

I'm curious about your use cases -- do you prefer to work with the TorchSharp source code directly, instead of using the NuGet package that's published?

**Comment by JimFFM** [comment]
![image](https://user-images.githubusercontent.com/59052120/122803906-849ae280-d2c7-11eb-9f38-e6df8fb3db73.png)


<img src="https://user-images.githubusercontent.com/59052120/122803906-849ae280-d2c7-11eb-9f38-e6df8fb3db73.png" alt="New TorchSharp Test Project" width="300" height="300">

**Comment by GeorgeS2019** [comment]
Currently, the TorchSharp repository is a good project to illustrate CI/CD pipeline for eventually targeting 3 different OS ( Windows, Linux, and MacOS) flawlessly.  However, if the goal is to encourage more new users to break apart the repository to create more test and example projects), we need to focus on solutions that result in **easy adoption or buy in** to TorchSharp.

This could mean more work in creating more repositories. However, this also mean less challenge in creating flawless CI/CD pipelines.

The goal is to get more user participation and engagement so we start to see more user playgrounds in using TorchSharp for simple to complex codes.

**Comment by GeorgeS2019** [comment]
@dsyme I slowly learn and appreciate the ninja/kungfu skills involved in configuring both Dotnet build and VS2019 to work.

I tried to add in addition to TorchSharpRecipes, the TorchSharpRecipies.**WithCudaBinaries**-

The first is OK **after I git pull your latest comits**. However the second one **WithCudaBinaries** fail. 

Could you please check what went wrong.


<img src="https://user-images.githubusercontent.com/49812372/122971646-8cbe5500-d38f-11eb-9524-876f717163af.png" alt="New TorchSharp Test Project" width="300" height="400">
