### ISSUE TITLE
Random number from uniform distribution works but not bernoulli : pytorch versus TorchSharp in jupyter

### ISSUE THREAD

**Issue by GeorgeS2019** [xamarin/TorchSharp#303]
This uses the [yet to merge] combined pull requests of 301 and 302 
Based on [PyTorch Recipes Chapter 2](https://github.com/Apress/pytorch-recipes/blob/master/Torch_AI_2.ipynb)

# Random number from uniform distribution
### PyTorch
![image](https://user-images.githubusercontent.com/49812372/124404068-948bdb00-dd39-11eb-998c-9b8757fe4317.png)

### TorchSharp
![image](https://user-images.githubusercontent.com/49812372/124404087-a5d4e780-dd39-11eb-9174-65edabd27ae2.png)

# torch.bernoulli
### PyTorch
![image](https://user-images.githubusercontent.com/49812372/124404148-f2202780-dd39-11eb-8943-8266547cfc07.png)

### TorchSharp
![image](https://user-images.githubusercontent.com/49812372/124404206-2c89c480-dd3a-11eb-9162-ba74ed581c8a.png)

![image](https://user-images.githubusercontent.com/49812372/124404227-4c20ed00-dd3a-11eb-9c1a-dafd129e175c.png)

FYI => there are no Unit Tests for **TorchSharp Tensor bernoulli** [as well as **multinomial**] and it is not sure if both works

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- thanks for pointing out the missing API. There is a 'bernoulli_' declared on Tensor, just like the uniform, but there's clearly missing from the 'torch' module itself.

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- in addition to this, the entire 'torch.distributions' module is missing in TorchSharp. It'll take more than a little work to get that implemented, so I won't fix that part of it in this PR.

I'll open an issue to track.

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- I believe that this has been addressed in the update to PR #302.
