### ISSUE TITLE
Request for netstandard 2.0 nuget package

### ISSUE THREAD

**Issue by LittleLittleCloud** [xamarin/TorchSharp#306]
Hi Torchsharp, firstly, thanks for the amazing work. I'd like to try torchsharp in my project, which is target towards net472. But currently, torchsharp only targets netcoreapp3.1. Could you provide a netstandard2.0 package on Nuget, thanks.

**Comment by dsyme** [comment]
Hi @LittleLittleCloud 

TorchSharp will only be available for .NET Core (most likely net5.0 or net6.0 will be required).

Thanks

**Comment by ekagra-ranjan** [comment]
I too had this constraint for my project. I am using older version of TorchSharp (0.3.52259) and libtorch-cpu (1.5.6) that supports netstandard 2.0. This older version uses dotnet syntax as it is dated before when TorchSharp switched to Pythonic styled syntax. However, it has all the required functionality that my project needs so its fine for my use case.
