### ISSUE TITLE
libtorch-cuda-11.1 NuGet package is missing

### ISSUE THREAD

**Issue by lostmsu** [xamarin/TorchSharp#312]
Is this because the packages are too big?

**Comment by dsyme** [comment]
You need to choose Linux or Windows - yes, because one package merging these would be overkill

**Comment by NiklasGustafsson** [comment]
@lostmsu -- is this still an issue, or can it be closed?

**Comment by lostmsu** [comment]
@NiklasGustafsson it sort of is, but I guess it is more about efficiency of C# compiler/NuGet, which should only download OS-specific packages until instructed to publish a version, that is OS-independent.
