### ISSUE TITLE
`Tensor.detach`

### ISSUE THREAD

**Issue by lostmsu** [xamarin/TorchSharp#314]
Is there an analogue of [`Tensor.detach`](https://pytorch.org/docs/stable/generated/torch.Tensor.detach.html) in TorchSharp?

**Comment by NiklasGustafsson** [comment]
@lostmsu:

Yes. I remember adding it recently. If it's not in the latest merged PR, then it's in the one waiting to be merged.

We haven't done a release to NuGet in a while, though. Once #313 goes in, we should do one. That will be the massively breaking change release, as the API has been restructured along Python lines.

**Comment by NiklasGustafsson** [comment]
This was addressed in PR #313.
