### ISSUE TITLE
`AccessViolationException` in `TorchTensor.Dispose`

### ISSUE THREAD

**Issue by lostmsu** [xamarin/TorchSharp#315]
By following memory guide, I added `GC.Collect` into my code after every epoch. The first such call after an epoch of training crashes with

> Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
>    at TorchSharp.Tensor.TorchTensor.THSTensor_dispose(IntPtr)
>    at TorchSharp.Tensor.TorchTensor.THSTensor_dispose(IntPtr)
>    at TorchSharp.Tensor.TorchTensor.Dispose(Boolean)
>    at TorchSharp.Tensor.TorchTensor.Finalize()

Repro steps (requires .NET 3.1 Core and C# 9, Windows only):
1. Clone https://github.com/losttech/Torch.Siren.git
2. Checkout TorchSharpBugs/315
3. go to `app` subfolder
4. `dotnet run path_to_image.jpg`

When done from command line, simply crashes with `Fatal error. Internal CLR error. (0x80131506)`
When run from Visual Studio (use `Siren.sln` at the root), also displayed the stack trace.

Without the call to `GC.Collect` memory is leaking fast.

**Comment by lostmsu** [comment]
I think I have a fix.

**Comment by lostmsu** [comment]
See minimal repro: https://github.com/xamarin/TorchSharp/pull/316/files#diff-1f04e1c804d5f49ad256443abd868c0e382e907ba5c738f67e8a5247ccbd6304

**Comment by NiklasGustafsson** [comment]
@lostmsu:

I left some comments in the PR. I'm now wondering if there aren't more of these bugs. There are two more places where handles are exchanged between native and managed code and at least temporarily "owned" by a Tensor object.

**Comment by NiklasGustafsson** [comment]
I found two other locations with the same problem. All three are addressed in PR #317.

Thanks for finding this!

**Comment by NiklasGustafsson** [comment]
I tried to check whether there was also a threading issue, but I could not establish a repro of pytorch/pytorch#19029. I did add a unit test for it, but it's not failing right now.

**Comment by NiklasGustafsson** [comment]
Fixed with #317 having been merged.
