### ISSUE TITLE
A few inconsistencies with the new naming

### ISSUE THREAD

**Issue by lostmsu** [xamarin/TorchSharp#318]
1. I believe the entire contents of `torch.functional` are misplaced.
2. `CustomModule` is a nested class inside `torch.nn`, but `Sequential` is directly in `TorchSharp.Modules` (personally prefer the second variant).

**Comment by NiklasGustafsson** [comment]
@lostmsu -- thanks! We've discussed #2 elsewhere, but #1 seems like something that needs investigation. I'll look into it today.

**Comment by lostmsu** [comment]
I guess n1 was not too detailed, but the problem is existence of both `torch.functional` and `torch.nn.functional`.

**Comment by NiklasGustafsson** [comment]
@lostmsu -- yup, that whole namespace shouldn't exist. It was created by sloppy placement of '}' characters in a number of files. PR #319 addresses it.

**Comment by NiklasGustafsson** [comment]
@lostmsu: I will address the CustomModule issue in an upcoming PR -- the class does not exist in Pytorch, as you have pointed out, and I will remove it.
