### ISSUE TITLE
Create unit tests for all API bindings.

### ISSUE THREAD

**Issue by NiklasGustafsson** [xamarin/TorchSharp#33]
We should create unit tests for all the API bindings.

**Comment by interesaaat** [comment]
Connected with this, we should also refactor the structure of the project with Tester moved to Sample, Test containing unit tests. I also would like to have a solution structure similar to ML.NET with src and test dirs, src containing TorchSharp (and TorchTensor) and Samples, and test containing the tests.

**Comment by NiklasGustafsson** [comment]
I agree with that. Maybe also come up with a more official-sounding hierarchical namespace while we're at it (since it typically affects the folder structure). The libtorch bindings will be the low-level API that everything else uses, so it should perhaps not be in the top-level namespace.

**Comment by interesaaat** [comment]
Totally agree.

**Comment by dsyme** [comment]
Closing as specifically ATen related, see https://github.com/xamarin/TorchSharp/pull/129
