### ISSUE TITLE
Bug with conversion to Scalar

### ISSUE THREAD

**Issue by gbaydin** [xamarin/TorchSharp#331]
While working on DiffSharp with @dsyme I noticed the following bug with the creation of `Scalar` types from dotnet numeric types.

It looks like all integer types get mapped to `Int64` and all floating point types get mapped to `Float64`.

Here's a bit of F# code and its output that shows the problem:

```fsharp
open TorchSharp

let vbool = true
let sbool = Scalar.op_Implicit vbool
printfn "%A %A" (vbool.GetType()) sbool.Type

let vint8 = 2y
let sint8 = Scalar.op_Implicit vint8
printfn "%A %A" (vint8.GetType()) sint8.Type

let vbyte = 2uy
let sbyte = Scalar.op_Implicit vbyte
printfn "%A %A" (vbyte.GetType()) sbyte.Type

let vint16 = 2s
let sint16 = Scalar.op_Implicit vint16
printfn "%A %A" (vint16.GetType()) sint16.Type

let vint32 = 2
let sint32 = Scalar.op_Implicit vint32
printfn "%A %A" (vint32.GetType()) sint32.Type

let vint64 = 2L
let sint64 = Scalar.op_Implicit vint64
printfn "%A %A" (vint64.GetType()) sint64.Type

let vfloat32 = 2.f
let sfloat32 = Scalar.op_Implicit vfloat32
printfn "%A %A" (vfloat32.GetType()) sfloat32.Type

let vfloat64 = 2.
let sfloat64 = Scalar.op_Implicit vfloat64
printfn "%A %A" (vfloat64.GetType()) sfloat64.Type
```

Output:
```
System.Boolean Bool
System.SByte Int64
System.Byte Int64
System.Int16 Int64
System.Int32 Int64
System.Int64 Int64
System.Single Float64
System.Double Float64
```

I could follow TorchSharp code until

https://github.com/xamarin/TorchSharp/blob/93a03123c7cf6657d479e89bb55902ae9db17794/src/TorchSharp/Scalar.cs#L150

and 

https://github.com/xamarin/TorchSharp/blob/c5dde7a5bf811b1f6c81f9278e7da858a6d29cd0/src/Native/LibTorchSharp/THSTorch.cpp#L121

but I can't see immediately why the problem arises.

I'm using TorchSharp 0.91.52719 and libtorch 1.9.0.

**Comment by NiklasGustafsson** [comment]
@gbaydin -- is this sufficiently covered? As far as I'm can tell, it's a feature of the native library to widen all scalars to the largest compatible type.
