### ISSUE TITLE
Fix doc strings

### ISSUE THREAD

**Issue by NiklasGustafsson** [xamarin/TorchSharp#35]
For a number of the functions on tensors, the doc strings are either incomplete or missing information. A systematic scrubbing needs to be done, consulting the libtorch source code and docs in order to complete the generated API.

**Comment by NiklasGustafsson** [comment]
The doc strings have improved, and are there for all the TypeGenerator methods. However, some of the arguments have empty explanation strings.

**Comment by interesaaat** [comment]
Documentation is also missing on the C# API of TorchSharp. The C API should be ok, maybe we can simply port the doc from there.

**Comment by NiklasGustafsson** [comment]
I'm going to close this issue -- the doc string situation has improved significantly.
