### ISSUE TITLE
Using TorchSharp Unit Tests as precursors to TorchSharp onboarding documentation

### ISSUE THREAD

**Issue by GeorgeS2019** [xamarin/TorchSharp#396]
This issue is a reference to get more .NET community awareness of TorchSharp and to engage in contributing to TorchSharp documentation for new users ([suggestion as discussed here](https://github.com/dotnet/TorchSharp/discussions/395))

**Comment by NiklasGustafsson** [comment]
@GeorgeS2019 -- if you think that a reorganization of the unit tests is a good pedagogical tool (I have no opinion for or against), a PR that implements your suggested reorg will be welcome. I'll assign this to you for now.
