### ISSUE TITLE
Using TorchSharp in .Net Framework

### ISSUE THREAD

**Issue by evo11x** [xamarin/TorchSharp#408]
I have tried to use TorchSharp in a .NET framework project, but the Nuget package was incompatible with .NET Framework project, then I have manually downloaded the package and I have extracted the files with WinRAR.
I have added the TorchSharp reference to the .NET Framework 4.8 app. The project is compiling but when it hits the first line var device = torch.cuda.is_available() ? torch.CUDA : torch.CPU; I get this error

System.IO.FileNotFoundException: 'Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral

I have tried to find a fix but with no luck.

Any help would be appreciated.
Thanks!

**Comment by dsyme** [comment]
Is there any reason you cant use a .net core 5 project? Usually it's realistic for code involving tensor programming 

Thanks
