### ISSUE TITLE
Zero-copy tensor creation

### ISSUE THREAD

**Issue by pkese** [xamarin/TorchSharp#524]
I'm having some slightly complex code for tensor creation in which I need to programmatically gather data from various places.

What I do is: I fill a flat 1D array with nested for loops and use strides to put the right values into the right indexes.  
Then I pass that array to torch, which copies it into a tensor.

So I was wondering if it would be possible to somehow do this without extra allocations and copying by e.g.
- passing `Memory<T>` to torch and let torch take ownership of it without copying, or
- creating an empty uninitialized tensor and then somehow getting a flat `Span<T>` or `Memory<T>` into that tensor's raw memory to fill it in (maybe a delegate callback with Span<T> with optional strides).

Is there something of this kind available in TorchSharp?

**Comment by lostmsu** [comment]
`Tensor.bytes`

**Comment by pkese** [comment]
Oh, this is perfect. Thanks.



*(Note to myself):*
```fsharp
let floats = System.Runtime.InteropServices.MemoryMarshal.Cast<byte,float32>(tensor.bytes)
```
