### ISSUE TITLE
Tensor operation - progress tracking

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/TorchSharp#6]
- [x] maskedFill
- [x] maskedCopy
- [x] maskedSelect

- [x] squeeze
- [x] squeeze1d
- [x] unsqueeze1d

- [x] nonzero

- [x] indexSelect
- [x] indexCopy
- [x] indexAdd
- [x] indexFill
- [x] take
- [x] put

- [x] gather
- [x] scatter
- [x] scatterAdd
- [x] scatterFill

- [x] dot

- [x] minall
- [x] maxall
- [x] medianall
- [x] sumall
- [x] prodall

- [x] neg
- [x] cinv

- [x] add
- [x] sub
- [x] add_scaled
- [x] sub_scaled
- [x] mul
- [x] div
- [x] lshift
- [x] rshift
- [x] fmod
- [x] remainder
- [x] clamp
- [x] bitand
- [x] bitor
- [x] bitxor

- [x] cadd
- [x] csub
- [x] cmul
- [x] cpow
- [x] cdiv
- [x] clshift
- [x] crshift
- [x] cfmod
- [x] cremainder
- [x] cbitand
- [x] cbitor
- [x] cbitxor

- [x] addcmul
- [x] addcdiv

- [x] addmv
- [x] addmm
- [x] addr

- [x] addbmm
- [x] baddbmm

- [x] match

- [x] numel
- [x] max
- [x] min
- [x] kthvalue
- [x] mode
- [x] median
- [x] sum
- [x] prod
- [x] cumsum
- [x] cumprod
- [x] sign
- [x] cross

- [x] cmax
- [x] cmin
- [x] cmaxValue
- [x] cminValue

- [x] zerosLike
- [x] onesLike
- [x] diag
- [x] eye
- [x] arange
- [x] range
- [x] randperm

- [x] sort
- [x] topk
- [x] tril
- [x] triu
- [x] cat
- [x] catArray

- [x] equal

- [x] ltValue
- [x] leValue
- [x] gtValue
- [x] geValue
- [x] neValue
- [x] eqValue

- [x] ltValueT
- [x] leValueT
- [x] gtValueT
- [x] neValueT
- [x] eqValueT

- [x] ltTensor
- [x] leTensor
- [x] gtTensor
- [x] geTensor
- [x] neTensor
- [x] eqTensor

- [x] ltTensorT
- [x] leTensorT
- [x] gtTensorT
- [x] geTensorT
- [x] neTensorT
- [x] eqTensorT

- [x] pow
- [x] tpow

- [x] abs
- [x] sigmoid
- [x] log
- [x] lgamma
- [x] digamma
- [x] trigamma
- [x] polygamma
- [x] log10
- [x] log1p
- [x] log2
- [x] exp
- [x] expm1
- [x] cos
- [x] acos
- [x] cosh
- [x] sin
- [x] asin
- [x] sinh
- [x] tan
- [x] atan
- [x] atan2
- [x] tanh
- [x] erf
- [x] erfc
- [x] erfinv
- [x] sqrt
- [x] rsqrt
- [x] ceil
- [x] floor
- [x] round
- [x] abs
- [x] trunc
- [x] frac
- [x] lerp
- [x] mean
- [x] std
- [x] var
- [x] norm
- [x] renorm
- [x] dist
- [x] histc
- [x] bhistc
- [x] meanall
- [x] varall
- [x] stdall
- [x] normall
- [x] linspace
- [x] logspace
- [x] dirichlet_grad
- [x] logicalAndAll
- [x] logicalAnyAll
- [x] logicalAnd
- [x] logicalAny

**Comment by markusweimer** [comment]
@migueldeicaza, how did you make this list? Which header file contains it?

**Comment by migueldeicaza** [comment]
I looked at the public symbols from libtorhc.a, and then found where they are defined, which is a little tricky - they use macros that expand to the public symbols:

./include/TH/generic/THTensorMath.h

Among other tensor operations.

**Comment by NiklasGustafsson** [comment]
The operator on this list now all have .NET bindings.

**Comment by interesaaat** [comment]
I am going to close this issue since it looks that Niklas completed all operators.
