### ISSUE TITLE
dotnet build -c Release fails on Linux

### ISSUE THREAD

**Issue by motus** [xamarin/TorchSharp#66]
It probably happens when we try to build a (multi-platform?) NuGet package. I get the following error:

`/usr/share/dotnet/sdk/2.1.403/Sdks/NuGet.Build.Tasks.Pack/build/NuGet.Build.Tasks.Pack.targets(199,5): error : Could not find a part of the path '/home/motus/devel/TorchSharp/windows'. [/home/motus/devel/TorchSharp/TorchSharp/TorchSharp.csproj]`

Observed on my Ubuntu 18.10 laptop with dotnet sdk 2.1.403.

Is there a way to build a release *without* creating a nuget package? Alternatively, maybe we should bundle (or `git submodule`?) libtorch libraries for all platforms we build a nuget for? @migueldeicaza you probably already have the solution in mind..

**Comment by migueldeicaza** [comment]
Hello,

This should be fixed now, can you check if that works?

**Comment by motus** [comment]
Yes, it works now. Thank you!
