### ISSUE TITLE
Sort out half-float support

### ISSUE THREAD

**Issue by migueldeicaza** [xamarin/TorchSharp#69]
Currently .NET lacks support for half-float, so we do not surface these data types in the API.

We should figure out if we should at least provide some interop APIs, even if we can not operate directly on the half values.

**Comment by tannergooding** [comment]
The CoreFX API proposal for adding a `Half` interchange type is here: https://github.com/dotnet/corefx/issues/25702

It has not gone to API review yet, as we determined it may need a dedicated review session.

**Comment by dsyme** [comment]
This is done, for now.  We can move to depend on Merkli.Half or another until the point the Corefx Half becomes available
