### ISSUE TITLE
Discussion: SNT integration with TorchSharp

### ISSUE THREAD

**Issue by interesaaat** [xamarin/TorchSharp#71]
Given that PR #51 got merged I am opening this issue to log some of the issues we where discussing over there. The main issue probably is whether TorchSharp should remain into its own assembly or get merged with SNT. One point in favor of being its own assembly is that it looks it can live with no other dependency and the mapping with the native Torch layer is lean and simpler. The main question is however: do we aspect developers to use TorchSharp tensors directly or will they always use System Numeric Tensors? Because if this is the case, it will make more sense to merge the two projects, have TorchSharp tensors as internals and unify the TorchSharp Storage class with NartiveMemory so that we can avoid unnecessary objects.

**Comment by markusweimer** [comment]
I believe we should *not* make the `TorchTensor` types `internal` or such. They serve an important purpose for interop, and will probably always support a richer API than the `System.Numerics.Tensor` wrapper for them. For instance, they can be on GPU or other special-device memory.

That being said, I am somewhat synpathetic to have the `System.Numeric.Tensor` types in the same project as the `TorchTensor` ones, and to maybe even fuse the two types (e.g. `TorchTensor` can extend `Tensor` or such). That increases the use of `System.Numeric.Tensor` and therefor serves the goal of having a homogenous (exchange) type for Tensors across .NET.

**Comment by interesaaat** [comment]
> For instance, they can be on GPU or other special-device memory.

Isn't this an implementation detail? I can definitely see a flag in (SNT) `TorchTensor` storing if the tensor is in CPU or GPU and properly routing the calls to the TorchSharp tensor.

I agree that fusing the 2 tensors types together will be good, but it all depends on what we thing about  TorchSharp tensor: if it is designed to be directly consumed or not.

**Comment by migueldeicaza** [comment]
I thin we need to consider TorchSharp a 1:1 binding, intended for interop purposes, and should stand on its own.

**Comment by migueldeicaza** [comment]
Got a link to MemoryManager and NativeMemory?

**Comment by interesaaat** [comment]
`NativeMemory` is used for example [here](https://github.com/xamarin/TorchSharp/blob/42d89892a53835422016c59c74baf8a5ffaa37e4/SNT/TypeGenerator.cs#L16). It extends `MemoryManager` (which is defined [here](https://github.com/dotnet/coreclr/blob/master/src/System.Private.CoreLib/shared/System/Buffers/MemoryManager.cs))

**Comment by dsyme** [comment]
I have factored out the AtenSharp and SNT components (now called AtenSharp.Numerics.Tensors) to a separate project https://github.com/fsprojects/AtenSharp
