### ISSUE TITLE
Implement (TorchScript) model scoring

### ISSUE THREAD

**Issue by motus** [xamarin/TorchSharp#72]
We need to be able to load a model (trained in Python/TorchScript) from a file and use it for scoring in .NET. For that, we have to create a wrapper for libtorch C++ function

```cpp
TORCH_API std::shared_ptr<script::Module> torch::jit::load(const std::string& filename);
```

and the method

```cpp
IValue torch::jit::script::Module::forward(std::vector<IValue> inputs);
```

(plus some supporting classes and methods)

**Comment by interesaaat** [comment]
Fixed in #80
