### ISSUE TITLE
DllNotFoundException: caffe2

### ISSUE THREAD

**Issue by bemoregt** [xamarin/TorchSharp#73]
Hi, @krukow @duncanmak @JosephHill @motus @migueldeicaza 

I met this error when runs.

DllNotFoundException: caffe2

What's wrong to me?

OSX Mojave, Xamarin WB 1.5.x

from @bemoregt.

**Comment by motus** [comment]
@bemoregt that means it cannot find `libcaffe2.so` in your library path. the simplest (but hacky) solution for now is to add the path to your libtorch libraries to `LD_LIBRARY_PATH`
