### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by Oceania2018** [xamarin/TorchSharp#74]
Hi gentleman,
Is this project still active?

**Comment by interesaaat** [comment]
Hey, yes it is still active. I am currently working on [this](https://github.com/interesaaat/TorchSharp/tree/LibTorchSharpFirstTest) branch.

**Comment by Oceania2018** [comment]
Is this project initialized by Microsoft?

**Comment by interesaaat** [comment]
Yes.

**Comment by Oceania2018** [comment]
Could we trying to keep the syntax same as much as possible?
Like [TensorFlow.NET](https://github.com/SciSharp/TensorFlow.NET).

**Comment by mdabros** [comment]
Hi @interesaaat, sounds great that the project is still active 👍  
Will your work eventually be pull requested back into the master branch in `xamarin/TorchSharp/`? So we can have a new release/nuget package?

**Comment by interesaaat** [comment]
Hey @mdabros, yes that's my plan. @Oceania2018, what do you mean? I believe we are following PyTorch API (or at least the c++ API) plus some C# notation.

**Comment by Oceania2018** [comment]
@interesaaat I've raise a new dissucss issue #76
