### ISSUE TITLE
efficient way to update by coordinates

### ISSUE THREAD

**Issue by alexkitasov** [xamarin/TorchSharp#777]
Hi TorchSharp team,
is there anyway to update tensor by coords.
for example I have followigh tensor

[ 1 , 7 , 7 ]

0   0   0   0   0   0   0
0   0   0   0   0   0   0
0   0   0   0   0   0   0
0   0   0   0   0   0   0
0   0   0   0   0   0   0
0   0   0   0   0   0   0
0   0   0   0   0   0   0

and I want to get:

0   0   0   0   0   0   0
0   0   0   0   0   0   0
0   1   1   1   1   1   0
0   1   0   0   0   1   0
0   1   1   1   1   1   0
0   0   0   0   0   0   0
0   0   0   0   0   0   0

or maybe this is easier:

0   0   0   0   0   0   0
0   0   0   0   0   0   0
0   1   1   1   1   1   0
0   1   1   1   1   1   0
0   1   1   1   1   1   0
0   0   0   0   0   0   0
0   0   0   0   0   0   0

should this be in discussion? not sure if this should be as issue

**Comment by kaiidams** [comment]
Content of a tensor array can be modified with indexer.

```cs
using TorchSharp;
using static TorchSharp.torch;
var x = torch.zeros(new long[] { 1 , 7 , 7 });
x[TensorIndex.Colon, TensorIndex.Slice(2, 5), TensorIndex.Slice(1, 6)] = 1;
x[TensorIndex.Colon, TensorIndex.Slice(3, 4), TensorIndex.Slice(2, 5)] = 0;
```

We also have Gitter room if you want to ask something casually. https://gitter.im/dotnet/TorchSharp

**Comment by alexkitasov** [comment]
thank you @kaiidams.
so there is no function that can override 2d area of one tensor with 2d tensor in one step?

**Comment by NiklasGustafsson** [comment]
So, for the full experience (try it in C# notebook with VS Code:

```C#
var t = torch.zeros(1,7,7);
t[.., 2..5, 1..6] = torch.ones(3,5);
t[..,3,2..5] = torch.zeros(3);
```
or

```C#
var t = torch.zeros(1,7,7);
t[.., 2..5, 1..6] = 1;
t[..,3,2..5] = 0;
```

See dotnet/TorchExamples for some tutorials that are great as a starting point for playing around with the features.

![image](https://user-images.githubusercontent.com/1791495/194359787-e3152502-f0ca-4656-a5f6-2acf2b70bc6b.png)
