### ISSUE TITLE
Complete error handling to the C# API 

### ISSUE THREAD

**Issue by interesaaat** [xamarin/TorchSharp#86]
Some of the methods are already wrapped into try/catch statements. We need to make sure that all methods have proper error handling.

**Comment by dsyme** [comment]
THSTensor.cpp has been done

These remain:

    THSAutograd.cpp
    THSData.cpp
    THSJIT.cpp
    THSNN.cpp
    THSTorch.cpp

**Comment by dsyme** [comment]
This is complete
