### ISSUE TITLE
Add scalar-tensor operations using C# numeric types for scalar

### ISSUE THREAD

**Issue by joemoorhouse** [xamarin/TorchSharp#94]
e.g. to remove need for ToScalar() in  weights.Eq(1.ToScalar()).Sum(new[] { 1L }) * (-1).ToScalar() + 0.5.ToScalar();

**Comment by joemoorhouse** [comment]
Could add implicit conversion via
public static implicit operator Scalar(double value){…} etc? Not sure if any undesirable consequences (will try it out).

**Comment by joemoorhouse** [comment]
Seems to work https://github.com/joemoorhouse/TorchSharp
Adding some more operators < <= etc; but just to check, is there any automatic code generation endeavor going on in parallel?

**Comment by interesaaat** [comment]
This is great! No, we are not working on the code generation issue for the moment. (hopefully we will soon)

**Comment by interesaaat** [comment]
@joemoorhouse any chance we can get a PR soon-ish. I think we fixed the build issues and we want to push the 0.2 release.

**Comment by joemoorhouse** [comment]
Yes, will do
