### ISSUE TITLE
Add a functional F# API

### ISSUE THREAD

**Issue by interesaaat** [xamarin/TorchSharp#97]
A la [Keras functional API](https://keras.io/getting-started/functional-api-guide/)

**Comment by Kavignon** [comment]
I’d be very much interested by this!

**Comment by dsyme** [comment]
I'm closing this as I'm not currently in favour of having a separate API for F# in this repository - espcially as from the F# perspective a lot of the rationale for doing work here is to provide a suitable backend for DiffSharp.  

We should just make the API equally usable from C# and F# for now.
